[package]
name = "globe"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.6"
pollster = "0.4"
wgpu = "24.0.0"
winit = { version = "0.30.8", features = ["android-native-activity"] }
